In [43]:
import numpy as np # Import NumPy library and alias it as 'np' for easy access

# 1. Vectors, Matrices, Tensors

In [44]:
x = np.array([1,2,3,4,5,6,7]) # Create a NumPy array (Vector) 'x' with elements 1 through 7
x  # Output the contents of the array 'x'

array([1, 2, 3, 4, 5, 6, 7])

In [46]:
x.shape # Get the shape (dimensions) of the array 'x'

(7,)

In [47]:
A = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]]) # Create a 2D NumPy array (Matrix) 'A' with 4 rows and 3 columns
A  # Output the contents of the array 'A'

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [48]:
A.shape # Get the shape (dimensions) of the 2D array 'A'

(4, 3)

In [49]:
T = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]], [[10,20,30],[40,50,60],[70,80,90],[100,110,120]]]) # Create a 3D tensor 'T' with shape (2, 4, 3): 2 matrices, each of size 4x3
T # Output the contents of the 3D tensor 'T'

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9],
        [ 10,  11,  12]],

       [[ 10,  20,  30],
        [ 40,  50,  60],
        [ 70,  80,  90],
        [100, 110, 120]]])

In [50]:
T.shape # Print the shape of the 3D tensor 'T'

(2, 4, 3)

In [51]:
print(len(x)) # Print the number of elements in the 1D array 'x'
print(len(A)) # Print the number of rows in the 2D array 'A'
print(len(T)) # Print the number of matrices in the 3D tensor 'T'

7
4
2


In [52]:
A_transpose = A.T # Transpose the 2D array 'A', swapping rows with columns, and store it in 'A_transpose'
A_transpose # Output the contents of the transposed array 'A_transpose'

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [53]:
print(A.shape) # Print the shape of the original 2D array 'A' (number of rows and columns)
print(A_transpose.shape)  # Print the shape of the transposed array 'A_transpose' (number of columns and rows)

(4, 3)
(3, 4)


In [54]:
B = np.array([[11,21,31],[41,51,61],[71,81,91],[101,111,121]]) # Create a 2D NumPy array 'B' with 4 rows and 3 columns
B # Output the contents of the array 'B'

array([[ 11,  21,  31],
       [ 41,  51,  61],
       [ 71,  81,  91],
       [101, 111, 121]])

In [55]:
C = A + B # Add the arrays 'A' and 'B' element-wise, storing the result in 'C'
A, B, C # Output the contents of arrays 'A', 'B', and 'C'

(array([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]),
 array([[ 11,  21,  31],
        [ 41,  51,  61],
        [ 71,  81,  91],
        [101, 111, 121]]),
 array([[ 12,  23,  34],
        [ 45,  56,  67],
        [ 78,  89, 100],
        [111, 122, 133]]))

* Broadcasting

In [56]:
D = A + 4 # Add 4 to each element of the array 'A', storing the result in 'D'
A, D # Output the contents of arrays 'A' and 'D'

(array([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]),
 array([[ 5,  6,  7],
        [ 8,  9, 10],
        [11, 12, 13],
        [14, 15, 16]]))

In [59]:
B = np.array([[13], [14], [15], [16]]) # Create a 2D column vector 'B' with shape (4, 1)
A, B # Output the contents of the arrays 'A' and 'B'

(array([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]),
 array([[13],
        [14],
        [15],
        [16]]))

In [60]:
print(A+B) # Add array 'A' and column vector 'B' element-wise, broadcasting 'B' to match the shape of 'A', and print the result

[[14 15 16]
 [18 19 20]
 [22 23 24]
 [26 27 28]]


* Multiplying Matrices and Vectors

In [27]:
A = np.array([[1,2],[2,4],[3,6]])  # Create a 2D array 'A' with shape (3, 2)
B = np.array([[1,2,3],[2,4,6]]) # Create a 2D array 'B' with shape (2, 3)
A, B # Output the contents of the arrays 'A' and 'B'

(array([[1, 2],
        [2, 4],
        [3, 6]]),
 array([[1, 2, 3],
        [2, 4, 6]]))

In [29]:
A.shape, B.shape  # Print the shapes of the arrays 'A' and 'B'

((3, 2), (2, 3))

In [30]:
C = np.dot(A,B) # Compute the dot product of arrays 'A' and 'B', storing the result in 'C'
C # Output the contents of the resulting array 'C'

array([[ 5, 10, 15],
       [10, 20, 30],
       [15, 30, 45]])

In [31]:
C = A.dot(B) # Compute the dot product of arrays 'A' and 'B' using the dot method, storing the result in 'C'
C # Output the contents of the resulting array 'C'

array([[ 5, 10, 15],
       [10, 20, 30],
       [15, 30, 45]])

In [32]:
C = np.array([[10,20,30],[20,40,60]]) # Create a 2D array 'C' with shape (2, 3)
C # Output the contents of the array 'C'

array([[10, 20, 30],
       [20, 40, 60]])

* Matrices multiplication is distributive

In [34]:
D = A.dot(B+C) # Compute the dot product of array 'A' with the result of array 'B' plus array 'C', storing the result in 'D'
D # Output the contents of the resulting array 'D'

array([[ 55, 110, 165],
       [110, 220, 330],
       [165, 330, 495]])

In [35]:
D = A.dot(B) + A.dot(C) 
# Compute the dot product of array 'A' with 'B', add it to the dot product of array 'A' with 'C', and store the result in 'D'
D # Output the contents of the resulting array 'D'

array([[ 55, 110, 165],
       [110, 220, 330],
       [165, 330, 495]])

* Matrices multiplication is associative